POST http://localhost:3333/api/auth/login HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "email": "andromadusv2@gmail.com",
    "password": "meowmeow"
}

###
POST http://localhost:3333/api/auth/signup HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "full_name": "Andromadus Naruto",
    "email": "andromadusv2@gmail.com",
    "password": "meowmeow"
}

###
GET http://localhost:3333/api/auth/check-auth HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdWlkIjoiY2w4MnhtdnM3MDAwODNtaGdqcndzeWxidCIsImlhdCI6MTY2MzIzOTEzNSwiZXhwIjoxNjYzMjQyNzM1fQ.37vqG84giLNlqXSh1wZDor_UrzwL2oTCQa80ZBj_-tg